name: rail-fence-cipher
version: 1.1.0.1

ghc-options: -Wall

dependencies:
  - base

library:
  exposed-modules: RailFenceCipher
  source-dirs: src
  dependencies:
    - array

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - rail-fence-cipher
      - hspec
